version: '3.8'

services:
  vanilla:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.16.3
      CONSOLE: "false"
    ports:
      - 25565:25565
    volumes:
      - /minecraft/vanilla:/data
